[workspace]
resolver = "2"
members = ["handler", "migration", "entity"]

[workspace.dependencies]
tokio = { version = "1.35.0", features = ["full"] }
async-trait = "0.1.74"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
