[workspace]
resolver = "2"
members = ["handler", "bot-client"]

[workspace.dependencies]
tokio = { version = "1.35.0", features = ["full"] }
async-trait = "0.1.74"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
bytes = "1.5.0"
thiserror = "1.0.50"
