version: "3"

networks:
  default:

services:
  mysql:
    image: mariadb:10
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-pass}
      MYSQL_USER: ${MYSQL_USER?Variable MYSQL_USER not set}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD?Variable MYSQL_PASSWORD not set}
      MYSQL_DATABASE: ${MYSQL_DATABASE?Variable MYSQL_DATABASE not set}
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    expose:
      - 3306
    healthcheck:
      test: mysqladmin ping -h localhost -u root -ppass
      interval: 1s
      timeout: 10s
      retries: 60
    ports:
      - "3306:3306"
    networks:
      - default

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - "8080:8080"
    networks:
      - default
    depends_on:
      mysql:
        condition: service_healthy

  app:
    build: .
    image: h23w_01-backend
    environment:
      BOT_ACCESS_TOKEN: ${BOT_ACCESS_TOKEN?Variable BOT_ACCESS_TOKEN not set}
      VERIFICATION_TOKEN: ${VERIFICATION_TOKEN?Variable VERIFICATION_TOKEN not set}
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS?Variable ALLOWED_ORIGINS not set}
      CHECK_AUTH: ${CHECK_AUTH?Variable CHECK_AUTH not set}
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
