[package]
name = "domain"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-trait.workspace = true
bytes.workspace = true
uuid.workspace = true
chrono.workspace = true
serde.workspace = true
mockall = "0.12.0"
shaku.workspace = true
traq.workspace = true
