[package]
name = "cron"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio-cron-scheduler.workspace = true
async-trait.workspace = true
chrono.workspace = true
futures.workspace = true

domain.path = "../domain"
indoc = "2.0.4"
