[package]
name = "handler"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
tokio.workspace = true
serde.workspace = true
async-trait.workspace = true
rocket = { version = "0.5", features = ["json"] }
traq-bot-http = "0.8.0"
