//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub use super::card::Entity as Card;
pub use super::card_content::Entity as CardContent;
pub use super::publish_channel::Entity as PublishChannel;
